### ISSUE TITLE
Great python dude

### ISSUE THREAD

**Issue by marcostudios** [ModalSeoul/shigetora#1]
So in your words "Shavit is a 15 years old sub-human"... 

With this project you're clearly a grown up person and a nice developer to get in touch developer. gg

**Comment by ModalSeoul** [comment]
If you're going to try and counter something I've said, at least make sense when doing so. Otherwise the entire act of what you're attempting is moot.

**Comment by ModalSeoul** [comment]
That's unfortunate. I was really hoping you'd try to take this further. Does that mean no more screenshot-harvesting for me?

Damn.
